---
title: "Readme.Rmd"
author: "Gani Agadilov, Yawei Ge, Yudi Zhang"
date: "4/17/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggrepel)
library(shiny)
library(lubridate)
```

#Read the data
```{r}
url <- "https://data.iowa.gov/resource/m3tr-qhgy.json"
data <- jsonlite::read_json(url)
```

#Cleaning the data

```{r}
download.file("https://stat585-at-isu.github.io/materials-2019/data/story-sales.zip", "data/story-sales.zip")
iowaliquor <- unzip("data/story-sales.zip", junkpaths = T, exdir = "data")
```


- Spatial:
```{r}
iowaliquor <- read_csv("data/Iowa_Liquor_Sales-Story.csv")
iowaliquor <- iowaliquor %>% 
  mutate(longlat = str_extract(`Store Location`, pattern = ".*?\\(.*?\\)"),
         lat = as.numeric(str_replace(longlat, "\\((.*?),\\s*.*\\)", "\\1")),
         long = as.numeric(str_replace(longlat, ".*?,\\s*(.*)\\)", "\\1"))) %>%
  select(-longlat) %>%
  filter(lat < 42.3, long > -93.8) %>%
  filter(lat > 41.8, long < -93.2) %>%
  mutate(City = tolower(City))

# save map data for Story county
story <- map_data("county") %>%
  filter(subregion == "story")

# Plot1: Story County Liquor Sales: #observations

story %>%
  ggplot() + 
  geom_path(aes(x = long, y = lat, group = group)) + 
  geom_count(data = iowaliquor, aes(x = long, y =lat, color = City), alpha = 0.5) +
  ggtitle("Story County Liquor Sales: #observations") + 
  theme_light()
  
# Plot2: Ames City: #observations
ggplot() +
  geom_count(data = iowaliquor %>% filter(City == "ames"), 
             aes(x = long, y =lat), alpha = 0.5, color = "pink2") +
  ggtitle("Ames City Liquor Sales: #observations")

# Plot3: Ames City: #observations and top five stores
# create summary data for stores
storedata <- iowaliquor %>%
  mutate(`Store Name` = tolower(`Store Name`)) %>%
  group_by(`Store Name`) %>%
  filter(!is.na(`Sale (Dollars)`)) %>%
  summarise(n = n(), 
            volume_liters = sum(`Volume Sold (Liters)`),
            sale_dollars = sum(`Sale (Dollars)`), 
            long = mean(long), 
            lat = mean(lat),
            City = City[1]) %>%
  ungroup() %>%
  arrange(desc(n))
# plot
ggplot(data = iowaliquor %>% filter(City == "ames"),
       aes(x = long, y =lat)) +
  geom_count(alpha = 0.5, color = "pink2") +
  geom_label_repel(data = storedata %>% filter(City == "ames") %>% head(n = 5), 
                   aes(label = `Store Name`), 
                   hjust = 1, vjust = -7) +
  ggtitle("Ames City: #observations and top five stores")

# Plot4: Ames City: Store and Volumes

storedata %>% filter(City == "ames") %>%
  ggplot(aes(x = long, y = lat, size = volume_liters)) + 
  geom_point() + 
  ggtitle("Ames City: Store and Volumes")
  

# Plot5: Non-spacial plot

storedata %>% 
  ggplot(aes(x = volume_liters, y = sale_dollars)) + 
  geom_point() + 
  geom_label_repel(data = storedata %>% filter(volume_liters == max(volume_liters)),
                   aes(label = `Store Name`))

# Plot6: Sams Club is so different

storedata %>% 
  ggplot(aes(x = volume_liters, y = sale_dollars)) + 
  geom_point(aes(size = n)) + 
  geom_label_repel(data = storedata %>% filter(volume_liters == max(volume_liters)),
                   aes(label = `Store Name`)) + 
  ggtitle("Sams Club is so different")

# Plot7: Sams Club is so different

storedata %>% 
  ggplot(aes(x = n, y = sale_dollars)) + 
  geom_point() + 
  geom_label_repel(data = storedata %>% filter(volume_liters == max(volume_liters)),
                   aes(label = `Store Name`)) + 
  ggtitle("Sams Club is so different")
```
-Temporial:
```{r}
iowaliquor <- read_csv("data/Iowa_Liquor_Sales-Story.csv")
iowaliquor <- iowaliquor %>% 
  mutate(longlat = str_extract(`Store Location`, pattern = ".*?\\(.*?\\)"),
         lat = as.numeric(str_replace(longlat, "\\((.*?),\\s*.*\\)", "\\1")),
         long = as.numeric(str_replace(longlat, ".*?,\\s*(.*)\\)", "\\1"))) %>%
  select(-longlat) %>%
  dplyr::filter(lat < 42.3, long > -93.8) %>%
  dplyr::filter(lat > 41.8, long < -93.2) %>%
  mutate(City = tolower(City))

iowaliquor <- iowaliquor %>% mutate(Date = lubridate::mdy(Date))%>% 
               mutate(Date = format(as.Date(Date), "%Y"))

storedatayear <- iowaliquor %>%
  group_by(City,`Date`) %>% 
    dplyr::filter(!is.na(`Sale (Dollars)`)) %>%
    summarise(n = n(), 
              volume_liters = sum(`Volume Sold (Liters)`),
              sale_dollars = sum(`Sale (Dollars)`))%>%
  ungroup() 

 # Plot1: Ames : Sale dollars by year and city

storedatayear %>% dplyr::filter(City == "ames") %>%
    ggplot(aes(x = Date, y = sale_dollars)) +  geom_point()
    ggtitle("Sale dollars by year and city")
    
    
 # Plot2: Ames : Sale volumes by year and city

storedatayear %>% dplyr::filter(City == "ames") %>%
    ggplot(aes(x = Date, y = volume_liters)) +  geom_point()
    ggtitle("Volumes liters by year and city")

```


